apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloworld-go-ingress
  namespace: istio-system
spec:
  rules:
    - host: helloworld-go.default.<ingress_subdomain>
      http:
        paths:
          - path: /
            backend:
              serviceName: istio-ingressgateway
              servicePort: 80